### ISSUE TITLE
Error "__vite_ssr_import_0__.toRef is not a function"

### ISSUE THREAD

**Issue by mishabachkur** [DanSnow/vue-recaptcha#1177]
Hello. I encountered the following error.

`__vite_ssr_import_0__.toRef is not a function", "stack": "<pre><span class=\"stack internal\">at Module.useChallengeV2 (./node_modules/vue-recaptcha/dist/composables/challenge-v2.mjs:22:41)</span>\n<span class=\"stack internal\">at Module.useComponentV2 (./node_modules/vue-recaptcha/dist/composables/component-v2.mjs:8:105)</span>\n<span class=\"stack internal\">at setup (./node_modules/vue-recaptcha/dist/components/Checkbox.vue:25:44)</span>\n<span class=\"stack internal\">at _sfc_main.setup (./node_modules/vue-recaptcha/dist/components/Checkbox.vue:49:23)</span>\n<span class=\"stack internal\">at callWithErrorHandling (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:156:18)</span>\n<span class=\"stack internal\">at setupStatefulComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7190:25)</span>\n<span class=\"stack internal\">at setupComponent (./node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:7151:36)</span>\n<span class=\"stack internal\">at renderComponentVNode (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:614:15)</span>\n<span class=\"stack internal\">at Module.ssrRenderComponent (./node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:86:10)</span>\n<span class=\"stack\">at _sfc_ssrRender (./components/Company/Blocks/Form.vue:120:32)</span></pre>`

I suspect it occurred after I updated @nuxtjs/i18n to ^8.0.0-beta.12 and added "type": "module" to package.json

Has anyone encountered this before and knows how to resolve it?

The error only occurs on vue-recaptcha@^3.0.0-alpha.5. If I downgrade to version 3.0.0-alpha.4, everything is fine.

**Comment by DanSnow** [comment]
Closing as stale — no activity and relates to older Vue/vue-demi compatibility issues superseded by the current version. Please upgrade to the latest vue-recaptcha and open a new issue if the problem persists.
