### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by borkafight** [DanSnow/vue-recaptcha#346]
My raygun says:
```
at hasOwnProperty line , column (<anonymous>:0)
at Object.checkRecaptchaLoad line 1, column 7829
```
v.1.3.0

**Comment by ceigh** [comment]
Got it in my Sentry logger. This is most popular error here... So logs just says:

```shell
TypeError: Cannot convert undefined or null to object
  at hasOwnProperty(<anonymous>)
  at Object.checkRecaptchaLoad(/cabinet/_nuxt/vendors.app.e975eb8.js:2:148132)
  at f.mounted(/cabinet/_nuxt/vendors.app.e975eb8.js:2:149109)
```

Also i use vue-recaptcha as Nuxt plugin.

The error seems to occurs when VueRecaptcha component mounted.

**Comment by DanSnow** [comment]
@ceigh I cannot reproduce this. I just try to use `vue-recaptcha` with nuxt.js and it works correctly.
